context:
  version: "1.1.13"

package:
  name: sqlit-tui
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/sqlit-tui/sqlit_tui-${{ version }}.tar.gz
    sha256: 39e34360d8c168374986785020d6094a427a1423cfae27ccedf9f295195dbcd8

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - sqlit = sqlit.cli:main
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - textual >=6.10.0
    # for textual[syntax], has run_constrained on textual:
    - tree_sitter
    - tree_sitter_languages
    - textual-fastdatatable >=0.14.0
    - keyring >=24.0.0
    - docker-py >=7.0.0
    - sqlparse >=0.5.0

tests:
  - python:
      imports:
        - sqlit
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - sqlit --help

about:
  summary: The lazygit of SQL databases
  description: |
    A terminal UI for SQL Server, PostgreSQL, MySQL, SQLite, Oracle, and more
    Connect and query your database from your terminal in seconds.

    Supports all major databases: SQL Server, PostgreSQL, MySQL, SQLite, MariaDB, FirebirdSQL, Oracle, DuckDB, CockroachDB, ClickHouse, Snowflake, Supabase, CloudFlare D1, and Turso.

    Syntax highlighting. History. Vim-style keybindings.
  homepage: https://github.com/Maxteabag/sqlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
